# Generated by Django 2.2.7 on 2019-12-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191211_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_mail',
            field=models.BooleanField(default=False),
        ),
    ]
